// IMPORTANT: This file is auto-generated by FlutterFire CLI.
// Run: flutterfire configure
// in your project directory after setting up Firebase.
//
// Steps:
// 1. Go to https://console.firebase.google.com
// 2. Create project "kisan-dost-pk"
// 3. Add Android & iOS apps
// 4. Install FlutterFire CLI: dart pub global activate flutterfire_cli
// 5. Run: flutterfire configure --project=kisan-dost-pk
// 6. This will generate firebase_options.dart automatically
//
// Required Firebase Services to enable:
// - Authentication (Email/Password)
// - Cloud Firestore
// - Firebase Storage
// - Firebase Messaging (for push notifications)
//
// Firestore Security Rules (paste in Firebase console):
// rules_version = '2';
// service cloud.firestore {
//   match /databases/{database}/documents {
//     match /users/{userId} {
//       allow read: if request.auth != null;
//       allow write: if request.auth.uid == userId;
//     }
//     match /products/{productId} {
//       allow read: if request.auth != null;
//       allow create: if request.auth != null;
//       allow update, delete: if request.auth != null &&
//         resource.data.farmerId == request.auth.uid;
//     }
//     match /orders/{orderId} {
//       allow read: if request.auth != null &&
//         (resource.data.farmerId == request.auth.uid ||
//          resource.data.buyerId == request.auth.uid);
//       allow create: if request.auth != null;
//       allow update: if request.auth != null &&
//         (resource.data.farmerId == request.auth.uid ||
//          resource.data.buyerId == request.auth.uid);
//     }
//     match /mandi_rates/{rateId} {
//       allow read: if request.auth != null;
//       allow write: if false; // Admin only via console
//     }
//     match /transport_routes/{routeId} {
//       allow read: if request.auth != null;
//       allow create: if request.auth != null;
//       allow update, delete: if request.auth != null &&
//         resource.data.transporterId == request.auth.uid;
//     }
//     match /ratings/{ratingId} {
//       allow read: if request.auth != null;
//       allow create: if request.auth != null;
//     }
//   }
// }
//
// Firebase Storage Rules:
// rules_version = '2';
// service firebase.storage {
//   match /b/{bucket}/o {
//     match /products/{allPaths=**} {
//       allow read: if request.auth != null;
//       allow write: if request.auth != null;
//     }
//     match /profiles/{allPaths=**} {
//       allow read: if request.auth != null;
//       allow write: if request.auth != null;
//     }
//     match /payment_proofs/{allPaths=**} {
//       allow read: if request.auth != null;
//       allow write: if request.auth != null;
//     }
//   }
// }
