// File generated by FlutterFire CLI.
// Run: flutterfire configure --project=YOUR_PROJECT_ID
// This file will be AUTO-REPLACED when you run flutterfire configure.
// Keep it as is until then - it uses DefaultFirebaseOptions from your google-services.json

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// ⚠️  IMPORTANT: Replace these values with your actual Firebase config!
/// Get them from: Firebase Console → Project Settings → Your apps
///
/// HOW TO GET CORRECT VALUES:
/// 1. Install FlutterFire CLI: dart pub global activate flutterfire_cli
/// 2. Run: flutterfire configure
/// 3. This file will be auto-generated with correct values
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJYjkEo_GlHtm7ZVlFodQ7Sc-WY0Q3Q0s',
    appId: '1:109319033251:web:112cdf4ed0984fd31e8a16',
    messagingSenderId: '109319033251',
    projectId: 'kisan-dost-pk',
    authDomain: 'kisan-dost-pk.firebaseapp.com',
    storageBucket: 'kisan-dost-pk.firebasestorage.app',
  );

  // ⚠️ REPLACE THESE WITH YOUR ACTUAL VALUES FROM FIREBASE CONSOLE

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIzrlADd44oMYsDDzPuPcY3vNMlSl97F8',
    appId: '1:109319033251:android:8f4eec5c961262381e8a16',
    messagingSenderId: '109319033251',
    projectId: 'kisan-dost-pk',
    storageBucket: 'kisan-dost-pk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHz8omOp32zaCHhkMrfOU6cEdY7io1n-I',
    appId: '1:109319033251:ios:ab96f777006f44401e8a16',
    messagingSenderId: '109319033251',
    projectId: 'kisan-dost-pk',
    storageBucket: 'kisan-dost-pk.firebasestorage.app',
    iosBundleId: 'com.hanan.kisanDostPk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_MACOS_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
    iosBundleId: 'com.yourcompany.kisandostpk',
  );
}